### ISSUE TITLE
Bootstrap support?

### ISSUE THREAD

**Issue by artstalker** [GoshaFighten/Angular2DXWebpack#1]
Hi, I've tried to use your example and it works fine, but when I import bootstrap in vendor.ts it starts to throw an exception at runtime 
`bootstrap.js?f974:8Uncaught Error: Bootstrap's JavaScript requires jQuery(…)`
JQuery is also there in vendor.ts but it does not work by some reason..

This is mine vendor.ts file:
```
// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
// Other vendors for example jQuery, Lodash or Bootstrap
import 'jquery';
import 'bootstrap';

import './css/bootstrap.css';
import './css/bootstrap-theme.css';

import 'devextreme-angular';
```

**Comment by GoshaFighten** [comment]
@artstalker 
I think that you are getting the `jQuery is not defined` error. Bootstrap requires jQuery to be a global variable. To declare jQuery as a global variable, use the `webpack.ProvidePlugin` plugin as illustrated in the [file](https://github.com/GoshaFighten/Angular2DXWebpackDotNetCore/blob/master/webpack.config.vendor.js#L45). Add this plugin to the `webpack.common.js` file.
